In [1]:
import sqlalchemy as sqla
import sys
import time
import pandas as pd
import geopandas as gpd
import numpy as np
import requests
import datetime

In [2]:
# Chose the DB
db_input_2021 = input ("What database should we use?\n\n") 
# The following data uses data connected at our database

# Create the sqlalchemy engine
db_engine_2021 = sqla.create_engine(db_input_2021) #is taken by pd.read_sql_query function later on

# Test connection
try:
    db_connection = db_engine_2021.connect()
except Exception as exc:
    print("\nCouldn't connect to the database\n")
    try:
        print(exc.message, exc.args)
    except:
        pass
    sys.exit()
        
# If everything goes well, just be happy about it!
    print("\nHooray! We connected to the database!")

# Put dataframe into series

In [4]:
# CitySim timeseries
time_series = pd.read_sql_query("SELECT gmlid, time_array, values_array FROM citydb.nrg8_time_series WHERE interpolation_type='AverageInSucceedingInterval' AND acquisition_method='Simulation' ", db_engine_2021)
time_series

,gmlid,time_array,values_array
0,UUID_61db9cd0-5351-400e-9669-860c212c568b,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[19450, 19071, 19209, 19298, 19385, 19471, 195..."
1,UUID_706723ea-631b-4411-a515-2df824e73ac2,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[19450, 19071, 19209, 19298, 19385, 19471, 195..."
2,UUID_045cccca-d530-4ce1-865c-0266835d0d9c,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[19450, 19071, 19209, 19298, 19385, 19471, 195..."
3,UUID_38eadc0d-3eb6-460d-9900-e4d5e4d20520,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[19450, 19071, 19209, 19298, 19385, 19471, 195..."
4,_04A96FDB-A98B-418E-BC64-6F9C122ADB73,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[19450, 19071, 19209, 19298, 19385, 19471, 195..."
...,...,...,...
599,_ac2120fa-0c91-4799-9730-78d0e55cd779,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[22264, 21956, 22141, 22230, 22330, 22420, 225..."
600,_93C7BABB-8683-43BC-A206-372DBBED4194,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[22264, 21956, 22141, 22230, 22330, 22420, 225..."
601,UUID_60eb1be1-383f-4bd9-bde7-179a12f596e6,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[22264, 21956, 22141, 22230, 22330, 22420, 225..."
602,UUID_91c6ac61-f133-4cf3-b65a-b2489441719d,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[22264, 21956, 22141, 22230, 22330, 22420, 225..."
603,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,"[2019-01-01 00:00:00+01:00, 2019-01-01 01:00:0...","[22264, 21956, 22141, 22230, 22330, 22420, 225..."

In [5]:
time_df = time_series["time_array"].apply(pd.Series)

#Set the row indexes as gmlid
new_idx = time_series["gmlid"]
time_df = time_df.rename(index=new_idx)
time_df

,0,1,2,3,4,5,6,7,8,9,...,8750,8751,8752,8753,8754,8755,8756,8757,8758,8759
UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00
UUID_706723ea-631b-4411-a515-2df824e73ac2,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00
UUID_045cccca-d530-4ce1-865c-0266835d0d9c,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00
UUID_38eadc0d-3eb6-460d-9900-e4d5e4d20520,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00
_04A96FDB-A98B-418E-BC64-6F9C122ADB73,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
_ac2120fa-0c91-4799-9730-78d0e55cd779,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00
_93C7BABB-8683-43BC-A206-372DBBED4194,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00
UUID_60eb1be1-383f-4bd9-bde7-179a12f596e6,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00
UUID_91c6ac61-f133-4cf3-b65a-b2489441719d,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00
UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-01-01 00:00:00+01:00,2019-01-01 01:00:00+01:00,2019-01-01 02:00:00+01:00,2019-01-01 03:00:00+01:00,2019-01-01 04:00:00+01:00,2019-01-01 05:00:00+01:00,2019-01-01 06:00:00+01:00,2019-01-01 07:00:00+01:00,2019-01-01 08:00:00+01:00,2019-01-01 09:00:00+01:00,...,2019-12-31 14:00:00+01:00,2019-12-31 15:00:00+01:00,2019-12-31 16:00:00+01:00,2019-12-31 17:00:00+01:00,2019-12-31 18:00:00+01:00,2019-12-31 19:00:00+01:00,2019-12-31 20:00:00+01:00,2019-12-31 21:00:00+01:00,2019-12-31 22:00:00+01:00,2019-12-31 23:00:00+01:00

In [6]:
time_df = pd.DataFrame(time_df.stack())
time_df

                                                                        0
UUID_61db9cd0-5351-400e-9669-860c212c568b 0     2019-01-01 00:00:00+01:00
                                          1     2019-01-01 01:00:00+01:00
                                          2     2019-01-01 02:00:00+01:00
                                          3     2019-01-01 03:00:00+01:00
                                          4     2019-01-01 04:00:00+01:00
...                                                                   ...
UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff 8755  2019-12-31 19:00:00+01:00
                                          8756  2019-12-31 20:00:00+01:00
                                          8757  2019-12-31 21:00:00+01:00
                                          8758  2019-12-31 22:00:00+01:00
                                          8759  2019-12-31 23:00:00+01:00

[5291040 rows x 1 columns]

In [7]:
time_df.reset_index(inplace=True) 
time_df

,level_0,level_1,0
0,UUID_61db9cd0-5351-400e-9669-860c212c568b,0,2019-01-01 00:00:00+01:00
1,UUID_61db9cd0-5351-400e-9669-860c212c568b,1,2019-01-01 01:00:00+01:00
2,UUID_61db9cd0-5351-400e-9669-860c212c568b,2,2019-01-01 02:00:00+01:00
3,UUID_61db9cd0-5351-400e-9669-860c212c568b,3,2019-01-01 03:00:00+01:00
4,UUID_61db9cd0-5351-400e-9669-860c212c568b,4,2019-01-01 04:00:00+01:00
...,...,...,...
5291035,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,8755,2019-12-31 19:00:00+01:00
5291036,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,8756,2019-12-31 20:00:00+01:00
5291037,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,8757,2019-12-31 21:00:00+01:00
5291038,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,8758,2019-12-31 22:00:00+01:00
5291039,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,8759,2019-12-31 23:00:00+01:00

In [8]:
# Split timestamp to different data

time_df['year'] = [d.year for d in time_df.iloc[:,2]]
time_df['month'] = [d.month for d in time_df.iloc[:,2]]
time_df['hour'] = [d.hour for d in time_df.iloc[:,2]]
time_df['weekday'] = [d.weekday() for d in time_df.iloc[:,2]]
time_df['day_nbr'] = [d.day for d in time_df.iloc[:,2]]

In [9]:
time_df = time_df.drop(["level_1"], axis=1)
time_df = time_df.rename(columns={"level_0": "gmlid", 0: "timestamp"})

In [10]:
time_df

,gmlid,timestamp,year,month,hour,weekday,day_nbr
0,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 00:00:00+01:00,2019,1,0,1,1
1,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 01:00:00+01:00,2019,1,1,1,1
2,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 02:00:00+01:00,2019,1,2,1,1
3,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 03:00:00+01:00,2019,1,3,1,1
4,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 04:00:00+01:00,2019,1,4,1,1
...,...,...,...,...,...,...,...
5291035,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 19:00:00+01:00,2019,12,19,1,31
5291036,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 20:00:00+01:00,2019,12,20,1,31
5291037,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 21:00:00+01:00,2019,12,21,1,31
5291038,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 22:00:00+01:00,2019,12,22,1,31
5291039,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 23:00:00+01:00,2019,12,23,1,31

In [12]:
# Extract energy values 

energy_df = time_series["values_array"].apply(pd.Series)

#Set the row indexes as gmlid
new_idx = time_series["gmlid"]
energy_df = energy_df.rename(index=new_idx)

#Stack dataframe
energy_df = pd.DataFrame(energy_df.stack())

#Resent index
energy_df.reset_index(inplace=True)

In [13]:
energy_df

                                           level_0  level_1      0
0        UUID_61db9cd0-5351-400e-9669-860c212c568b        0  19450
1        UUID_61db9cd0-5351-400e-9669-860c212c568b        1  19071
2        UUID_61db9cd0-5351-400e-9669-860c212c568b        2  19209
3        UUID_61db9cd0-5351-400e-9669-860c212c568b        3  19298
4        UUID_61db9cd0-5351-400e-9669-860c212c568b        4  19385
...                                            ...      ...    ...
5291035  UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff     8755  23161
5291036  UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff     8756  23532
5291037  UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff     8757  23896
5291038  UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff     8758  24257
5291039  UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff     8759  24699

[5291040 rows x 3 columns]

In [16]:
# Merge data to obtain time and enrgy values dataframe
timeseries_output = pd.merge(time_df, energy_df, left_index=True, right_index=True, how='left').rename(columns={0: "energy_demand"})
timeseries_output = timeseries_output.drop(["level_0", "level_1"], axis=1)
timeseries_output

,gmlid,timestamp,year,month,hour,weekday,day_nbr,energy_demand
0,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 00:00:00+01:00,2019,1,0,1,1,19450
1,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 01:00:00+01:00,2019,1,1,1,1,19071
2,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 02:00:00+01:00,2019,1,2,1,1,19209
3,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 03:00:00+01:00,2019,1,3,1,1,19298
4,UUID_61db9cd0-5351-400e-9669-860c212c568b,2019-01-01 04:00:00+01:00,2019,1,4,1,1,19385
...,...,...,...,...,...,...,...,...
5291035,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 19:00:00+01:00,2019,12,19,1,31,23161
5291036,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 20:00:00+01:00,2019,12,20,1,31,23532
5291037,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 21:00:00+01:00,2019,12,21,1,31,23896
5291038,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 22:00:00+01:00,2019,12,22,1,31,24257
5291039,UUID_4c35702f-12fe-4fed-a08c-63e85683d2ff,2019-12-31 23:00:00+01:00,2019,12,23,1,31,24699